# Generated by Django 4.2.16 on 2024-09-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='winCount',
            field=models.IntegerField(default=0),
        ),
    ]
